services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: delivery_db
    volumes:
      - postgres_delivery_data:/var/lib/postgresql/data  
    ports:
      - '5433:5432'
    expose:
      - '5433'
    restart: always
    networks:
      - keycloak_network


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: abdo@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80' 
    expose:
      - '5050'
    restart: always
    networks:
      - keycloak_network


  keycloak:
      image: quay.io/keycloak/keycloak:26.1.1
      command: 
        - start-dev
      container_name: keycloak-delivery-app
      environment:
        - KC_HOSTNAME_PORT=8888
        - KC_HOSTNAME_STRICT_BACKCHANNEL=false
        - KC_HTTP_ENABLED=true
        - KC_HOSTNAME_STRICT_HTTPS=false
        - KC_HOSTNAME_STRICT=false
        - KC_HEALTH_ENABLED=true
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
        - KC_DB=postgres
        - KC_DB_URL=jdbc:postgresql://postgres/delivery_db
        - KC_DB_USERNAME=postgres
        - KC_DB_PASSWORD=postgres
      volumes:
        - keycloak_delivery_data:/opt/jboss/keycloak/standalone/data  
      ports:
        - '8888:8080'
      expose:
        - '8888'  
      restart: always
      depends_on:
        - postgres
      networks:
        - keycloak_network

  # backend:
  #   image: jira_backend
  #   container_name: jira_backend
  #   build:
  #     context: ./SpringBack
  #     dockerfile: Dockerfile
  #   ports:
  #     - '8081:8081'
  #   expose:
  #     - '8081'
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/jira_db
  #     - SPRING_DATASOURCE_USERNAME=postgres
  #     - SPRING_DATASOURCE_PASSWORD=postgres  
  #   restart: always
  #   depends_on:
  #     - keycloak
  #     - postgres
  #   networks:
  #     - keycloak_network        

  # frontend:
  #   image: jira_frontend
  #   container_name: jira_frontend
  #   build:
  #     context: ./AngularFront
  #     dockerfile: Dockerfile
  #   ports:
  #     - '4200:4200'
  #   expose:
  #     - '4200'
  #   environment:
  #     - KEYCLOAK_URL=http://localhost:8888
  #     - KEYCLOAK_REALM=jira-realm
  #     - KEYCLOAK_CLIENT_ID=angular-app
  #   restart: always
  #   networks:
  #     - keycloak_network    

volumes:
  keycloak_delivery_data: 
    driver: local
  postgres_delivery_data:
    driver: local

networks:
      keycloak_network:
        driver: bridge      